# -*- coding: utf-8 -*-
"""LLM_API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-V2g4txDQotFGvm2g4LZMkViAfHzZ7FL
"""

import requests

API_KEY = "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"
def summarize_text(text, style):
    try:
        prompt = f"Summarize the following text in {style} style:\n\n{text}"

        response = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {API_KEY}"},
            json={
                "model": "llama-3.1-8b-instant",
                "messages": [
                    {"role": "user", "content": prompt}
                ]
            }
        )

        data = response.json()
        return data["choices"][0]["message"]["content"]

    except Exception as e:
        return f"Error: {str(e)}"

def main():
    text = input("Enter text to summarize: ").strip()
    if not text:
        print("Enter some text")
        return

    print("\nChoose style: brief / detailed / bullet points")
    style = input("Enter style: ").strip()

    print("\nSummary\n")
    result = summarize_text(text, style)
    print(result)

if __name__ == "__main__":
    main()